# Generated by Django 5.1.3 on 2024-11-20 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='business',
            field=models.ForeignKey(default='378cbddd-e3eb-4367-8db8-1ed9de2e88a6', on_delete=django.db.models.deletion.CASCADE, related_name='business_incomes', to='business.business'),
            preserve_default=False,
        ),
    ]
