# Generated by Django 5.1.3 on 2024-11-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_currency_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='vat_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
