# Generated by Django 5.1.3 on 2024-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_is_compliant_business_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tax_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
